### ISSUE TITLE
Dealing with default border for newbies

### ISSUE THREAD

**Issue by moeenio** [locness3/scratch-profile-embed#26]
I got this message :
![Screenshot_2019-07-10 emojicom 🤙 - Collect feedback using emojis](https://user-images.githubusercontent.com/37651007/60980648-27edc980-a335-11e9-9ecb-a12666d61557.png)

Basically, we have two possibilities :
1. Showing how to remove the border on the site
2. Giving a code without border

Any advice @Andreto @MasterOfTheTiger @KennethSweezy ?

**Comment by MasterOfTheTiger** [comment]
Can you specify what you are talking about? Maybe a screenshot?

**Comment by Andreto** [comment]
Maybe a checkbox for "Frame Styling". When it's checked they get the code with our custom styling and if it's unchecked they get the blank code.

**Comment by moeenio** [comment]
> Can you specify what you are talking about? Maybe a screenshot?

I'm talking about the default iframe border.

**Comment by MasterOfTheTiger** [comment]
@locness3 Okay. So a button toggle would be the best solution in my opinion.

**Comment by moeenio** [comment]
Don't you think giving a code without border and no other one would be sufficient ?

**Comment by MasterOfTheTiger** [comment]
> Don't you think giving a code without border and no other one would be sufficient ?

I think you are right, unless there is a good reason to keep the border.
