### ISSUE TITLE
[Bug] On Netlify, Back to home link on changelog is wrong

### ISSUE THREAD

**Issue by moeenio** [locness3/scratch-profile-embed#28]
**Describe the bug**
Clicking the "Back to home" link on the changelog on the Netlify version of the site redirects to `scratch-profile-embed.netlify.com/scratch-profile-embed`.

**To Reproduce**
1. Go to the site's [Netlify deployment](https://scratch-profile-embed.netlify.com).
2. Click "View changelog"
3. Click "Back to home"

**Expected behavior**
It should redirect to the home page.

**OS and browser (please complete the following information):**
 - OS: macOS 10.11.6
 - Browser: Firefox
 - Version: 69.0b4 (dev edition)

**Comment by Andreto** [comment]
That's because `href="/scratch-profile-embed"`.
If it's going to go back to the landing page the href must be pointing to `/` or `/landing`.
The issue is that on the real site the page is hosted under a folder and not in a subdomain as the nestify deployment.

**Comment by moeenio** [comment]
I know what causes the bug @Andreto, but I'm filing it to keep track of what I'm doing and let others know what I'm doing.

**Comment by githubfan** [comment]
Also, on my website, the new profile isn't working at all, but I can still access the new site.
` deploy-preview-30--scratch-profile-embed.netlify.com/#Joshuay2`
This code above is not working

**Comment by moeenio** [comment]
Man, be on-topic. Create a new issue.

About your problem : the code available on the test website points to the "normal" version. You have to manually replace the URL in your embed code pon your website. I might change this later though.

**Comment by moeenio** [comment]
GitHub issues are meant to organize discussion about the project in _seperate_ topics, and to keep track of the project's progress. Not just to have threads to randomly throw your thoughts and problems in. I'm sorry man, but if you do this on larger projects, you will not be appreciated and your comment will not be taken into account.

**Comment by moeenio** [comment]
Guess we can close this since we're not using this page anymore.
