### ISSUE TITLE
Having a button to copy the embed code to clipboard

### ISSUE THREAD

**Issue by moeenio** [locness3/scratch-profile-embed#46]
Currently, user will have to select the generated embed code and press Ctrl-C to copy it to clipboard. And they may select some text outside the code accidently.

What would be great would be a `copy to clipboard` button. We can implement one with [clipboard.js](https://github.com/zenorocha/clipboard.js) or [simplecopy](https://github.com/kyle-rb/simplecopy).

Something like this, when hovering the code block, would be great :

![mockup](https://user-images.githubusercontent.com/37651007/67586444-ed783300-f751-11e9-889c-869bd758cdfb.png)

**Comment by githubfan** [comment]
I agree

**Comment by MasterOfTheTiger** [comment]
Are libraries necessary? Shouldn't there be a more native JS option?

**Comment by moeenio** [comment]
We could do without a library.

**Comment by Andreto** [comment]
I don't really remember how but I remember it was pretty easy with pure js when I did it on the gobocf project.

**Comment by Andreto** [comment]
Found it, just add this onclick to a button: `onclick="document.getElementById('textbox_id').select();document.execCommand('copy')"`

**Comment by moeenio** [comment]
>just add this onclick to a button: `onclick="document.getElementById('textbox_id').select();document.execCommand('copy')"`

@Andreto Yes I know you can do this, but I mentionned libraries so it is easier for someone to contribute and implement it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Andreto** [comment]
#47
