### ISSUE TITLE
Change contributor url

### ISSUE THREAD

**Issue by Andreto** [locness3/scratch-profile-embed#59]
I'm sorry for making a whole issue about this, but I recently changed the domain of my website back to https://andreto.github.io/. I would be glad if you could change the link in the contributor section to point to that URL. Thanks!

**Comment by moeenio** [comment]
That's fine :)
The link was fetched from github by the allcontributors bot; let's try re-invocating him!

**Comment by moeenio** [comment]
@all-contributors please add @Andreto for code, ideas, and review

**Comment by moeenio** [comment]
Weird, looks like it doesn't update. let's do that manually

**Comment by Andreto** [comment]
Thanks!

**Comment by moeenio** [comment]
You're welcome :)
