### ISSUE TITLE
Show featured project

### ISSUE THREAD

**Issue by moeenio** [locness3/scratch-profile-embed#9]
As suggested by this guy, and other people, 
![Screenshot of message saying "Is there a way to embed the thumbnail of featured project here?](https://user-images.githubusercontent.com/37651007/53073928-b6c68a80-34e9-11e9-9c4d-1711727b1bbe.png)

**Comment by sweezyio** [comment]
It looks like the Scratch API [already has the capability](https://en.scratch-wiki.info/wiki/Scratch_API_(2.0)#GET_.2Fproject.2F.3Cproject_id.3E.2F) to return the link of the thumbnail. However, it looks like it may require multiple requests:

1. Get the featured project ID
2. Request the project stats (including the thumbnail image link)

**Comment by moeenio** [comment]
@KennethSweezy True

**Comment by MasterOfTheTiger** [comment]
@locness3 Is a PR welcome for this?

**Comment by moeenio** [comment]
@MasterOfTheTiger Sure!

**Comment by moeenio** [comment]
Someone also said this :
![Screenshot_2019-04-28 emojicom 🤙 - Collect feedback using emojis](https://user-images.githubusercontent.com/37651007/56861900-c8bf2080-69a5-11e9-93d9-54075521a3e8.png)
I think it's better to have just the featured project, because this is what the user wants to show. Advice @MasterOfTheTiger @KennethSweezy ?

**Comment by MasterOfTheTiger** [comment]
I believe it would be best to have it show just the featured project, with maybe a button saying "See more projects my this user" or something of that nature.

**Comment by moeenio** [comment]
> I believe it would be best to have it show just the featured project, with maybe a button saying "See more projects my this user" or something of that nature.

There's a already a button to view profile, we don't need a new one @MasterOfTheTiger

**Comment by Andreto** [comment]
https://github.com/locness3/scratch-profile-embed/pull/25

**Comment by moeenio** [comment]
Guess we can close this! Thanks again @Andreto !
